
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0     
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=WattWiseAdmin
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data
        - /Users/luisharmata/Desktop/DataSystemsInput:/input_data

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8081"
      - "7077:7077"

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: wattwise
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_SECRET_KEY=mysecretkey
      - DATABASE_URL=postgresql+psycopg2://superset:superset@postgres:5432/wattwise
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home

volumes:
  nifi_data:
  pg_data:
  superset_home:

